### ISSUE TITLE
Yay, totally forgot to build some release xpi

### ISSUE THREAD

**Issue by minch-yoda** [minch-yoda/DownTheMoon#4]
subj

**Comment by minch-yoda** [comment]
Done

**Comment by NebelNidas** [comment]
Where can I download it from? The README says from the Releases section, but there are no build artifacts to be found.

**Comment by minch-yoda** [comment]
I had to remove all builds branded as "DownThemAll!", because only the source code is open source, but not the artworks.
Then I rebranded the project as DownTheMoon and started making the artworks, but suddenly the whole political situation in my country got crazy and I had to postpone any pet projects to deal with IRL issues.
Anyway I'll try to build it tomorrow with some bare bones art, that should do.

**Comment by minch-yoda** [comment]
> Where can I download it from?
Done: https://github.com/minch-yoda/DownTheMoon/releases
